pure-admin/vue-pure-admin

- src/utils/loaders/index.ts
为不同的 elment 变量 添加不同的类型。方便使用正确的类型推导
> 修改 loaders 组件 为 element 添加不同的类型

- src/components/countTo/index.ts
- src/components/selector/index.ts
- src/views/components/selector/index.vue
> fix: fix import path error

- index.html
在调用build/util/loadEnv()函数时会报process.cwd() is not a function
#44
> fix: process.cwd error

- src/layout/components/navbar.vue
- src/layout/components/sidebar/horizontal.vue
- src/style/sidebar.scss
style: [sidebar.scss] delete overflow-x: auto
> style: [sidebar.scss] delete overflow-x: auto

- src/views/welcome.vue
> fix: welcome.vue 柱状图在大屏下显示异常

- src/components/ReIcon/index.ts
- src/layout/components/sidebar/sidebarItem.vue
- src/plugins/element-plus/index.ts
支持ElementPlus icon组件和 FontAwesomeIcon
用法: 
```js
<component
:is="
findIconRegx(
onlyOneChild.meta.icon ||
(props.item.meta && props.item.meta.icon)
)
"
></component>
```
> feat(icon): findIcon function

- src/utils/storage/index.ts
修复sessionStorageProxy-getItem方法储存false数字和0等情况返回null问题。
> fix: 修复sessionStorageProxy-getItem方法储存false数字和0等情况返回null问题。

- src/utils/storage/responsive.ts
> fix: epThemeColor error

- src/utils/http/index.ts
- src/utils/http/types.d.ts
refactor: 拼写错误: PureHttpResoponse => PureHttpResponse
> refactor: 拼写错误: PureHttpResoponse => PureHttpResponse

- mock/user.ts
- src/layout/hooks/nav.ts
- src/store/modules/permission.ts
- src/store/modules/user.ts
- src/views/login.vue
> feat: 用户登录使用mock api, 可以使用test用户登录

- src/components/ReIcon/src/select.vue
- src/views/able/icon-select.vue
> feat:  icon-select 增强

- src/views/able/debounce.vue
> fix:修改防抖例1的文字说明

- CHANGELOG.zh_CN.md
- locales/zh-CN.yaml
- src/layout/components/navbar.vue
- src/layout/components/sidebar/horizontal.vue
- src/layout/components/sidebar/mixNav.vue
- src/store/modules/user.ts
- src/views/login/components/phone.vue
- src/views/login/index.vue
- src/views/login/utils/rule.ts
- `登陆`指渡过海洋或江河登上陆地。
- `登录`才是login的意思。
> docs: replace "登陆" with "登录"

- src/layout/components/tag/index.vue
> fix: 修复导航tab关闭其他标签页无法重置状态问题

- src/store/modules/app.ts
- src/store/modules/epTheme.ts
- src/store/modules/multiTags.ts
- src/store/modules/settings.ts
https://pinia.vuejs.org/zh/core-concepts/getters.html
> perf: pinia getters改成官方推荐写法

- src/views/login/utils/verifyCode.ts
1. 点击后，倒计时会有 1s 延时禁用的问题；
2. 基于问题1，会出现在 1s 内可以无限点击获取验证码的问题。
> fix: verify code countdown

- src/layout/components/search/components/SearchFooter.vue
- src/layout/components/search/components/SearchModal.vue
- src/layout/components/search/components/SearchResult.vue
- src/style/dark.scss
- src/style/element-plus.scss
如题，修复后效果如下：
https://github.com/pure-admin/vue-pure-admin/assets/36908524/c23ee965-044b-4599-87fd-d11a952e5775
> chore: 优化菜单搜索

- package.json
> chore: update `scripts-clean:cache` in `package.json`

- src/views/login/utils/rule.ts
https://jkchao.github.io/typescript-book-chinese/typings/typeAssertion.html#%E7%B1%BB%E5%9E%8B%E6%96%AD%E8%A8%80%E8%A2%AB%E8%AE%A4%E4%B8%BA%E6%98%AF%E6%9C%89%E5%AE%B3%E7%9A%84
这里用了类型断言，可以优化。
> types: update

- src/layout/frameView.vue
fix：frameView组件隐藏标签页时高度没有自适应 #703
> fix：修复内嵌页面`frameView`在隐藏标签页后高度没有自适应

- src/components/ReCropper/src/circled.css
- src/components/ReCropper/src/index.tsx
- src/components/ReIcon/src/hooks.ts
- src/components/ReIcon/src/types.ts
- src/components/ReSegmented/src/index.css
- src/components/ReSegmented/src/index.tsx
- src/components/ReSegmented/src/type.ts
- src/layout/components/panel/index.vue
- src/layout/components/setting/index.vue
- src/layout/hooks/useDataThemeChange.ts
- src/main.ts
- src/style/dark.scss
- src/style/element-plus.scss
- src/style/index.scss
- src/views/able/wavesurfer/index.vue
> perf: 更干净整洁的项目配置右侧弹出面板

- src/layout/components/tag/index.vue
tag/index.vue concatPath function has repeat condition!
> fix: rm tag repeat condition

- package.json
- pnpm-lock.yaml
- src/layout/components/tag/index.scss
- src/layout/components/tag/index.vue
- src/layout/hooks/useTag.ts
- src/views/login/index.vue
https://github.com/pure-admin/vue-pure-admin/assets/44761321/30ba586f-dbc5-4a77-ac5e-2959dbb3876a
> perf: 标签页可按滑动力度进行左右滑动

- src/layout/components/tag/index.scss
- src/layout/components/tag/index.vue
Reverts pure-admin/vue-pure-admin#887
> Revert "perf: 优化标签页灵动模式"

- src/style/login.css
> fix: 修复注册布局滚动条bug

- src/layout/components/sidebar/linkItem.vue
- src/layout/components/sidebar/logo.vue
- src/layout/components/sidebar/sidebarItem.vue
- src/layout/types.ts
- src/style/sidebar.scss
菜单支持a标签右键的所有浏览器行为（在新标签页中、新窗口中打开链接，拖拽到新标签页打开等）
> feat: 菜单支持`a`标签右键的所有浏览器行为（在新标签页中、新窗口中打开链接，拖拽到新标签页打开等）

- locales/en.yaml
- locales/zh-CN.yaml
- src/directives/index.ts
- src/directives/ripple/index.scss
- src/directives/ripple/index.ts
- src/router/modules/able.ts
- src/views/able/ripple.vue
- types/global.d.ts
element plus的组件样式太过于单调，新增这个material风格的特效指令，能让元素有更好的交互效果，尤其是element plus的按钮
> feat: 新增v-ripple指令(水波纹效果)

- src/style/login.css
> style: 修复`windwos`下点击注册页面会出现滚动条问题

- types/global-components.d.ts
types: update global-components.d
> types: update global-components.d

- src/components/ReDialog/index.vue
- src/components/ReDialog/type.ts
- src/views/components/dialog/index.vue
> feat: 函数式弹框`ReDialog`添加`Popconfirm`气泡确认框

- src/views/account-settings/components/Profile.vue
> perf: 优化账号设置-头像上传功能

- src/style/dark.scss
修复深色模式下设置FixedHeader为false时，背景色为白色问题
> style: update

- build/utils.ts
- vite.config.ts
> chore: revise typo

- src/views/login/index.vue
这个 pr 无法重新打开，所以我重新打开了一个 pr
新增了最右边的数字键盘回车监听
https://github.com/pure-admin/vue-pure-admin/pull/1163
> perf: 优化登录页
