src/layout/components/tag/index.vue
src/views/system/dict/index.vue

解决页面刷新后 `tag` 标签关闭其中一个所有都消失的问题

fix: fix bug

---

build/utils.ts
types/global.d.ts
vite.config.ts

自定义loadEnv函数，[process.env.NODE_ENV](https://github.com/xiaoxian521/vue-pure-admin/blob/main/build/utils.ts#L12)=undefined，并且采用[dotenv](https://github.com/motdotla/dotenv)组件包含node内置的[fs](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L101) 是undefined,所以采用Vite loadEnv，并保留loadEnv自定义函数

fix: process.env.node_env undefined

---

src/layout/components/navbar.vue
src/layout/components/sidebar/breadCrumb.vue
src/layout/components/sidebar/sidebarItem.vue
src/layout/components/tag/index.vue
src/layout/types.ts
src/router/index.ts
src/utils/i18n.ts

当router parent `meta`存在`i18n:true`时，children `meta`的`i18n`必须存在不管是否为`true | false`

fix:  i18n

---

src/router/utils.ts

fix: 修复动态路由子级长度为0时抛出异常

---

build/info.ts

当 vite.config.ts 的打包路径 build.outDir 不是默认值 dist 时, getPackageSize 方法会出错

chore(build): getPackageSize 的 folder 修改为动态从 vite 配置中获取

---

src/layout/components/notice/noticeItem.vue

哈喽，移动端通知栏点击tooltip的时候会出现点击穿透导致外层下拉框被关闭的情况; 所以我在h5的环境下给tooltip加了个禁止enterable的判断，看下是否可行，截图在issues中

fix: 修复移动端通知栏`tooltip`点击穿透问题

---

src/layout/components/tag/index.vue

导航tab打开过多，会导致点击关闭左侧标签页后，剩余的标签栏无法正常显示出来。
https://user-images.githubusercontent.com/74349832/220542511-875b1108-6119-476c-af98-c75ce09b6bb5.mp4

fix: 修复导航tab过多导致关闭左侧标签页无法正常显示

---

src/layout/components/sidebar/vertical.vue

视频如下，混合模式下刷新页签，左侧菜单会失联
https://github.com/pure-admin/vue-pure-admin/assets/31479917/2240c50c-8793-4dd3-afb3-cef8d97fbbee

fix: 修复在混合模式下刷新页签后，左侧菜单会消失闪一下的问题

---

src/components/RePureTableBar/src/bar.tsx
src/utils/http/index.ts

fix: 修复`PureTableBar`组件关闭列设置时在`windows`出现滚动条的问题以及修改错误字

---

src/layout/components/search/components/SearchModal.vue
src/layout/components/search/components/SearchResult.vue

搜索弹窗的top为5vh，为底部预留相同的5vh，去掉弹窗的头部和底部固定高度剩下的即为中间滚动区域的最大高度

perf: 优化菜单搜索弹窗高度

---

.env.staging

`vite build`命令中不需要将NODE_ENV设置为production，参考链接：
https://cn.vitejs.dev/guide/migration.html#production-builds-by-default
此pr也可消除执行`build:staging`时的警告消息：
> NODE_ENV=production is not supported in the .env file. Only NODE_ENV=development is supported to create a development build of your project. If you need to set process.env.NODE_ENV, you can set it in the Vite config instead.

feat: 移除多余的env配置项

---

src/views/components/dialog/form.vue
src/views/components/dialog/formPrimitive.vue
src/views/components/dialog/index.vue

`结合Form表单（第一种方式）`找不到监听子组件事件的方式，目前无法实现期待的功能。

feat: 函数式弹窗示例代码添加子组件`prop`为`primitive`类型的`demo`

---

src/views/welcome/index.vue

fix: github information in home page

---

src/main.ts

使用中发现，如果路由中有涉及使用到store里的变量， 且想做持久化时；会由于先加载路由后加载store ，导致持久化失败；
所以mian 里初始化 应该按顺序 加载plugin（如果有依赖关系）。

perf: 页面初始化时先加载`pinia`再加载`router`，兼容更多使用场景

---

src/layout/components/tag/index.scss
src/layout/components/tag/index.vue

tag中作为标题使用的原标签为router-link，这对于不含params或query的路由跳转没有影响，
但当标签页tag对应的页面route存在params或query时，由于router-link自带的对click事件的处理，tag自定义绑定的点击事件“@click="tagOnClick(item)”会与router-link同时对tag的点击事件进行响应和处理，从而导致两次router跳转，这可以通过router.beforeEach函数断点监测到。
发现缘由，我在一个页面的组件挂载函数中定义了通过query中的数据初始化页面数据的函数，结果函数报错提示undefined（被catch了没有导致页面出错），但是使用tag菜单的软刷新后，又恢复正常。于是发现了这个bug。以下是简单的复现过程：
① 启动完整版后，打开先三个标签
② 在src/router/index.ts 的 router.beforEach 处 打个 log breakpoint
③ 从“标签页操作”页面，跳转到“No.1 详细信息”
可以看到控制台在同一时间会输出两次，第一次为router-link的跳转，不带query；第二次为tag定义的处理函数的跳转，带上了query。
将router-link改成其他html标签即可解决这个小bug，不过css样式也得跟着改

fix: 当路由存在query并单击tag触发tags标签切换时，会调用两次router跳转

---

src/style/sidebar.scss

Fixed fixed-header's width calcuate with wrong value(210px) not sidebarWidth
修复了固定标题宽度计算使用固定值（210px）而不是侧边栏宽度的错误

style: update `src/style/sidebar.scss`

---

src/utils/http/index.ts

https://github.com/pure-admin/vue-pure-admin/issues/761#issuecomment-1770297957 頁面切換失效，經測試後是 /refreshToken 寫錯造成的
https://github.com/pure-admin/vue-pure-admin/blob/main/src/api/user.ts#L38
https://github.com/pure-admin/vue-pure-admin/blob/main/src/utils/http/index.ts#L76
另外補充一下，目前沒有任何針對 refresh 錯誤做出對應措施

fix: 接口`/refreshToken`改为`/refresh-token`

---

src/components/RePureTableBar/src/bar.tsx

PureTableBar内的pure-table列数过多的话，列设置的弹出框会影响到页面布局，要不要优化一下，

perf: 优化`PureTableBar`组件的列设置弹出框，设置最大高度，超出可滚动

---

public/platform-config.json
src/layout/components/panel/index.vue
src/layout/components/setting/index.vue
src/layout/components/sidebar/leftCollapse.vue
src/layout/hooks/useDataThemeChange.ts
src/layout/hooks/useLayout.ts
src/layout/index.vue
src/layout/theme/index.ts
src/store/modules/epTheme.ts
src/style/sidebar.scss
src/utils/responsive.ts
types/global.d.ts
types/router.d.ts

1. 亮白主题色`light`模式下，优化字体颜色，使其更鲜明，如下图
2. 移除`yellow`金色主题配色，我的天，辣眼睛，考虑到这种配色几乎没人用将其移除
3. 优化左侧菜单的右边框，使其不再突兀
4. 所有层级的子菜单字体大小跟顶级菜单保持一致都是`14px`
5. 默认亮白`light`主题配色，更符合`pure`纯净的定位，并按照一定的感官调整主题色顺序。当然你也可以按照 [此处代码](https://github.com/pure-admin/vue-pure-admin/pull/842/commits/abfc0cc56593c45cc6d9ff5958799d70ea0b92d7#diff-75aadcbcba4cfc5cbefe74a21eacf0965d82143123eb5efef6c8483a07132399) ，自行调整顺序
6. 修复亮白主题配色，切换暗色主题后再切回亮色主题时，无法恢复之前的亮白主题配色
之前：
https://github.com/pure-admin/vue-pure-admin/assets/44761321/c56b1d64-d214-454b-985e-d361749d4f37
之后：
https://github.com/pure-admin/vue-pure-admin/assets/44761321/b347e48f-6968-4718-bdb9-a127fce7ef0e
7. 统一亮白主题配色下顶部菜单和混合菜单的`logo`和右侧操作功能颜色

refactor: 优化主题色

---

src/views/login/index.vue

问题原因：
修复获取后端路由因网络原因，未等待initRouter执行完毕，loading已经置为false, 导致按钮可以继续点击；
复现：
延时initRouter函数的返回或切换到3G网可出现
解决：
等待initRouter执行完毕

登录按钮的loading问题

---

src/layout/frameView.vue

修复`iframe`页面重新加载时，`iframe`缓存失效问题。
刷新当前页面时，`iframeView.vue`中的`iframeSrc`只有是当前页面`path.includes(props.frameInfo?.fullPath) // true`，才重新赋值加载，其余缓存页面做忽略处理。

fix: 重新加载时，iframe keepAlive失效

---

src/views/login/index.vue

这是无意中发现的小问题，其实也不算是bug,就是鼠标点击登录后按回车仍然能够触发onLoing函数，本来觉得是小问题但是在精简版的在线预览测试的时候发现页面每次都会卡死，而完整版的在线预览测试时不会触发那么多次，下面图片是我把完整版拉到本地测试的，但是触发的次数明显比在线预览时的多

fix(function): 修复点击登录后再连续敲击回车会多次触发onLogin函数的问题

---

src/layout/components/tag/index.scss
src/layout/components/tag/index.vue
src/layout/hooks/useTag.ts
src/style/dark.scss

之前（鼠标操作标签页会有伸缩，点击关闭按钮较麻烦）
https://github.com/pure-admin/vue-pure-admin/assets/44761321/a24aed28-881f-4fb4-a6b2-1ff92eacaa02
之后（不再伸缩，准确定位关闭按钮）
https://github.com/pure-admin/vue-pure-admin/assets/44761321/705d59ab-b927-4162-b23f-b91d870f3ffb

style: 重构标签页`UI`，点击关闭按钮更方便

---

src/style/element-plus.scss
src/views/guide/index.vue

ElementPlus现已推出Tour组件，可以用于实现引导，因此为引导示例页添加了基于ElTour实现的引导：

feat: 添加基于`ElTour`实现的漫游式引导

---

src/components/ReSegmented/src/index.css
src/components/ReSegmented/src/index.tsx
src/views/components/segmented.vue

为`ReSegmented`分段控制器新增`block`属性，`block` 属性可以使其适合父元素宽度
在某些场景下，会存在这样的需求，且可以让布局显得更为优美协调，效果同[Ant Design(Segmented)](https://ant.design/components/segmented-cn#segmented-demo-block)
参考图：

feat(components): 为`segmented`组件新增`block`属性，可使其适合父元素宽度

---

src/components/ReSegmented/src/index.css
src/components/ReSegmented/src/index.tsx
src/views/components/segmented.vue

为`ReSegmented`分段控制器新增`size`属性，`size` 属性用于配置尺寸，来适应不同的场景需求
定义了三种尺寸：大(`large`)、默认(`default`)、小(`small`)
尺寸样式标准值均参考自[Ant Design(Segmented)](https://ant-design.antgroup.com/components/segmented-cn#segmented-demo-size)，包括高度、边距、圆角、边框线等
代码实现参考自[Ant Design Vue](https://github.com/vueComponent/ant-design-vue/tree/main/components/segmented)
已完善组件示例，它现在是这样的：

feat: `ReSegmented`分段控制器新增`size`属性，以便适配不同的场景

---

src/views/system/user/utils/hook.tsx

- 当用户avatar字段为空时，使用平台默认图片，以确保裁剪组件能正确加载

perf: 优化用户管理-裁剪图片上传功能

---

src/views/components/cascader.vue
src/views/components/collapse.vue
src/views/components/statistic.vue

admin发布的`5.3.0`整体看了下，有几个模块的文字缺漏，与其他模块不协调(强迫症抓狂！)
文字的查缺补漏：`代码位`=>`代码位置`，
顺便把`演示页加上代码位置提示`涉及的模块都检查了一遍，主要补充了统计组件模块、折叠面板模块、区域级联选择器模块，共计三个模块的文字

chore: revise typo

---

src/components/ReSegmented/src/index.tsx
src/views/components/segmented.vue

在`Form`表单中基本所有组件都支持整个组件的`disabled`

feat: 分段控制器组件添加全局禁用属性`disabled`

---

.github/workflows/linter.yml

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

workflow: update node-version

---

src/components/ReSegmented/src/index.tsx

修复`ReSegmented`尺寸首次调整造成的样式错位问题
在修复前，它是这样的：
-----------------
现在，它是这样的：

perf: 优化`ReSegmented`组件

---

src/plugins/elementPlus.ts
types/global-components.d.ts

chore: update `plugins/elementPlus.ts`

---

build/optimize.ts
index.html
locales/en.yaml
locales/zh-CN.yaml
package.json
pnpm-lock.yaml
src/router/enums.ts
src/router/modules/able.ts
src/router/modules/form.ts
src/router/modules/ganttastic.ts
src/router/modules/markdown.ts
src/router/modules/table.ts
src/router/modules/vueflow.ts
src/views/markdown/components/Vditor.vue
src/views/markdown/index.vue

wait: https://github.com/condorheroblog/vite-plugin-fake-server/issues/39

feat: 添加`Markdown`示例

---

src/views/login/index.vue

keypress事件已弃用，不推荐再使用，建议改为keydown事件，谢谢
MDN参考链接：https://developer.mozilla.org/zh-CN/docs/Web/API/Element/keypress_event

chore: 使用`keydown`替换`keypress`，`keypress`事件已弃用

---

src/router/index.ts
src/router/utils.ts

修复如下问题：
在管理员登录并退出后，path为'/'下的children信息未被重置；
下个普通用户登录时，管理员相关路由页面也能被此普通用户正常访问。
相关issue：
#1040

fix: 修复resetRouter未清空全部路由数据

---

src/layout/frame.vue

修改`重新加载`时frame组件控制iframe的方式，防止出现两次拦截确认导致的问题。

fix: 修复在内嵌同源`iframe`页面中，当其注册了`beforeunload`事件时，右键标签页点击`重新加载`导致浏览器弹出两次确认拦截的问题
